// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AppSettings struct {
	F95Username  string `json:"f95Username"`
	F95Connected bool   `json:"f95Connected"`
}

type F95Game struct {
	ThreadID    string   `json:"threadId"`
	ThreadURL   string   `json:"threadUrl"`
	Title       string   `json:"title"`
	Developer   string   `json:"developer"`
	Version     string   `json:"version"`
	CoverURL    string   `json:"coverUrl"`
	Description string   `json:"description"`
	Tags        []string `json:"tags"`
	Engine      string   `json:"engine"`
	F95Status   string   `json:"f95Status"`
	Screenshots []string `json:"screenshots"`
}

type F95SearchItem struct {
	ThreadID  string   `json:"threadId"`
	ThreadURL string   `json:"threadUrl"`
	Title     string   `json:"title"`
	Version   string   `json:"version"`
	Engine    string   `json:"engine"`
	Tags      []string `json:"tags"`
}

type F95SearchResult struct {
	Results    []*F95SearchItem `json:"results"`
	TotalPages int              `json:"totalPages"`
}

type Game struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Developer     string     `json:"developer"`
	CoverURL      string     `json:"coverUrl"`
	Status        GameStatus `json:"status"`
	DevStatus     DevStatus  `json:"devStatus"`
	MyVersion     string     `json:"myVersion"`
	LatestVersion string     `json:"latestVersion"`
	DownloadURL   string     `json:"downloadUrl"`
	Tags          []string   `json:"tags"`
	Notes         string     `json:"notes"`
	Description   string     `json:"description"`
	VndbID        *string    `json:"vndbId,omitempty"`
	F95Id         *string    `json:"f95Id,omitempty"`
	HasUpdate     bool       `json:"hasUpdate"`
	AddedAt       time.Time  `json:"addedAt"`
	UpdatedAt     time.Time  `json:"updatedAt"`
}

type GameFilter struct {
	Status    *GameStatus `json:"status,omitempty"`
	HasUpdate *bool       `json:"hasUpdate,omitempty"`
	Tag       *string     `json:"tag,omitempty"`
	Search    *string     `json:"search,omitempty"`
}

type GameInput struct {
	Title         string      `json:"title"`
	Developer     *string     `json:"developer,omitempty"`
	CoverURL      *string     `json:"coverUrl,omitempty"`
	Status        *GameStatus `json:"status,omitempty"`
	DevStatus     *DevStatus  `json:"devStatus,omitempty"`
	MyVersion     *string     `json:"myVersion,omitempty"`
	LatestVersion *string     `json:"latestVersion,omitempty"`
	DownloadURL   *string     `json:"downloadUrl,omitempty"`
	Tags          []string    `json:"tags,omitempty"`
	Notes         *string     `json:"notes,omitempty"`
	Description   *string     `json:"description,omitempty"`
	VndbID        *string     `json:"vndbId,omitempty"`
	F95Id         *string     `json:"f95Id,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type SyncResult struct {
	Total   int      `json:"total"`
	Updated int      `json:"updated"`
	Errors  []string `json:"errors"`
}

type VNDBPage struct {
	Results []*VNDBResult `json:"results"`
	Count   int           `json:"count"`
	More    bool          `json:"more"`
}

type VNDBResult struct {
	VndbID      string            `json:"vndbId"`
	Title       string            `json:"title"`
	Developer   string            `json:"developer"`
	CoverURL    string            `json:"coverUrl"`
	Tags        []string          `json:"tags"`
	Description string            `json:"description"`
	Screenshots []*VNDBScreenshot `json:"screenshots"`
}

type VNDBScreenshot struct {
	Thumbnail string `json:"thumbnail"`
	URL       string `json:"url"`
}

type DevStatus string

const (
	DevStatusOngoing   DevStatus = "ONGOING"
	DevStatusComplete  DevStatus = "COMPLETE"
	DevStatusAbandoned DevStatus = "ABANDONED"
)

var AllDevStatus = []DevStatus{
	DevStatusOngoing,
	DevStatusComplete,
	DevStatusAbandoned,
}

func (e DevStatus) IsValid() bool {
	switch e {
	case DevStatusOngoing, DevStatusComplete, DevStatusAbandoned:
		return true
	}
	return false
}

func (e DevStatus) String() string {
	return string(e)
}

func (e *DevStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DevStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DevStatus", str)
	}
	return nil
}

func (e DevStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DevStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DevStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GameStatus string

const (
	GameStatusPlaying   GameStatus = "PLAYING"
	GameStatusCompleted GameStatus = "COMPLETED"
	GameStatusWant      GameStatus = "WANT"
	GameStatusDropped   GameStatus = "DROPPED"
	GameStatusOnHold    GameStatus = "ON_HOLD"
)

var AllGameStatus = []GameStatus{
	GameStatusPlaying,
	GameStatusCompleted,
	GameStatusWant,
	GameStatusDropped,
	GameStatusOnHold,
}

func (e GameStatus) IsValid() bool {
	switch e {
	case GameStatusPlaying, GameStatusCompleted, GameStatusWant, GameStatusDropped, GameStatusOnHold:
		return true
	}
	return false
}

func (e GameStatus) String() string {
	return string(e)
}

func (e *GameStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameStatus", str)
	}
	return nil
}

func (e GameStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GameStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GameStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
