package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"avn-tracker/backend/internal/graph/generated"
	"avn-tracker/backend/internal/model"
	"avn-tracker/backend/internal/vndb"
	"context"
	"fmt"
)

// AddGame is the resolver for the addGame field.
func (r *mutationResolver) AddGame(ctx context.Context, input model.GameInput) (*model.Game, error) {
	return r.Repo.Create(ctx, input)
}

// UpdateGame is the resolver for the updateGame field.
func (r *mutationResolver) UpdateGame(ctx context.Context, id string, input model.GameInput) (*model.Game, error) {
	return r.Repo.Update(ctx, id, input)
}

// DeleteGame is the resolver for the deleteGame field.
func (r *mutationResolver) DeleteGame(ctx context.Context, id string) (bool, error) {
	err := r.Repo.Delete(ctx, id)
	return err == nil, err
}

// ImportFromVndb is the resolver for the importFromVNDB field.
func (r *mutationResolver) ImportFromVndb(ctx context.Context, vndbID string) (*model.Game, error) {
	vn, err := r.VNDB.GetVN(ctx, vndbID)
	if err != nil {
		return nil, err
	}

	release, _ := r.VNDB.GetLatestRelease(ctx, vndbID)

	coverURL := ""
	if vn.Image != nil {
		coverURL = vn.Image.URL
	}
	developer := ""
	if len(vn.Developers) > 0 {
		developer = vn.Developers[0].Name
	}
	tags := make([]string, 0, len(vn.Tags))
	for _, t := range vn.Tags {
		tags = append(tags, t.Name)
	}
	latestVersion := ""
	if release != nil {
		latestVersion = release.Version
	}

	input := model.GameInput{
		Title:         vn.Title,
		Developer:     &developer,
		CoverURL:      &coverURL,
		Tags:          tags,
		LatestVersion: &latestVersion,
		Description:   &vn.Description,
		VndbID:        &vndbID,
	}
	return r.Repo.Create(ctx, input)
}

// SyncLatestVersion is the resolver for the syncLatestVersion field.
func (r *mutationResolver) SyncLatestVersion(ctx context.Context, id string) (*model.Game, error) {
	game, err := r.Repo.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	if game == nil {
		return nil, fmt.Errorf("game %s not found", id)
	}
	if game.VndbID == nil {
		return nil, fmt.Errorf("game %s has no VNDB ID", id)
	}

	release, err := r.VNDB.GetLatestRelease(ctx, *game.VndbID)
	if err != nil {
		return nil, err
	}
	if release == nil {
		return game, nil
	}
	return r.Repo.UpdateLatestVersion(ctx, id, release.Version)
}

// ExportLibrary is the resolver for the exportLibrary field.
func (r *mutationResolver) ExportLibrary(ctx context.Context) (string, error) {
	return r.Repo.Export(ctx)
}

// ImportLibrary is the resolver for the importLibrary field.
func (r *mutationResolver) ImportLibrary(ctx context.Context, json string) (bool, error) {
	err := r.Repo.Import(ctx, json)
	return err == nil, err
}

// Games is the resolver for the games field.
func (r *queryResolver) Games(ctx context.Context, filter *model.GameFilter) ([]*model.Game, error) {
	return r.Repo.List(ctx, filter)
}

// Game is the resolver for the game field.
func (r *queryResolver) Game(ctx context.Context, id string) (*model.Game, error) {
	return r.Repo.Get(ctx, id)
}

// SearchVndb is the resolver for the searchVNDB field.
func (r *queryResolver) SearchVndb(ctx context.Context, query string, page *int, adultsOnly *bool) (*model.VNDBPage, error) {
	p := 1
	if page != nil {
		p = *page
	}
	adult := false
	if adultsOnly != nil {
		adult = *adultsOnly
	}

	resp, err := r.VNDB.Search(ctx, query, p, adult)
	if err != nil {
		return nil, err
	}

	results := make([]*model.VNDBResult, 0, len(resp.Results))
	for _, vn := range resp.Results {
		results = append(results, vnToResult(&vn))
	}

	return &model.VNDBPage{
		Results: results,
		Count:   resp.Count,
		More:    resp.More,
	}, nil
}

// GetVNDBGame is the resolver for the getVNDBGame field.
func (r *queryResolver) GetVNDBGame(ctx context.Context, vndbID string) (*model.VNDBResult, error) {
	vn, err := r.VNDB.GetVN(ctx, vndbID)
	if err != nil {
		return nil, err
	}
	return vnToResult(vn), nil
}

// vnToResult converts a VNDB API VN to the GraphQL model.
func vnToResult(vn *vndb.VN) *model.VNDBResult {
	coverURL := ""
	if vn.Image != nil {
		coverURL = vn.Image.URL
	}
	developer := ""
	if len(vn.Developers) > 0 {
		developer = vn.Developers[0].Name
	}
	tags := make([]string, 0, len(vn.Tags))
	for _, t := range vn.Tags {
		tags = append(tags, t.Name)
	}
	shots := make([]*model.VNDBScreenshot, 0, len(vn.Screenshots))
	for _, s := range vn.Screenshots {
		thumb := s.Thumbnail
		if thumb == "" {
			thumb = s.URL
		}
		shots = append(shots, &model.VNDBScreenshot{Thumbnail: thumb, URL: s.URL})
	}
	return &model.VNDBResult{
		VndbID:      vn.ID,
		Title:       vn.Title,
		Developer:   developer,
		CoverURL:    coverURL,
		Tags:        tags,
		Description: vn.Description,
		Screenshots: shots,
	}
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
