package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"avn-tracker/backend/internal/graph/generated"
	"avn-tracker/backend/internal/model"
	"context"
	"fmt"
)

// AddGame is the resolver for the addGame field.
func (r *mutationResolver) AddGame(ctx context.Context, input model.GameInput) (*model.Game, error) {
	return r.Repo.Create(ctx, input)
}

// UpdateGame is the resolver for the updateGame field.
func (r *mutationResolver) UpdateGame(ctx context.Context, id string, input model.GameInput) (*model.Game, error) {
	return r.Repo.Update(ctx, id, input)
}

// DeleteGame is the resolver for the deleteGame field.
func (r *mutationResolver) DeleteGame(ctx context.Context, id string) (bool, error) {
	err := r.Repo.Delete(ctx, id)
	return err == nil, err
}

// ImportFromVndb is the resolver for the importFromVNDB field.
func (r *mutationResolver) ImportFromVndb(ctx context.Context, vndbID string) (*model.Game, error) {
	vn, err := r.VNDB.GetVN(ctx, vndbID)
	if err != nil {
		return nil, err
	}

	release, _ := r.VNDB.GetLatestRelease(ctx, vndbID)

	coverURL := ""
	if vn.Image != nil {
		coverURL = vn.Image.URL
	}
	developer := ""
	if len(vn.Developers) > 0 {
		developer = vn.Developers[0].Name
	}
	tags := make([]string, 0, len(vn.Tags))
	for _, t := range vn.Tags {
		tags = append(tags, t.Name)
	}
	latestVersion := ""
	if release != nil {
		latestVersion = release.Version
	}

	input := model.GameInput{
		Title:         vn.Title,
		Developer:     &developer,
		CoverURL:      &coverURL,
		Tags:          tags,
		LatestVersion: &latestVersion,
		Description:   &vn.Description,
		VndbID:        &vndbID,
	}
	return r.Repo.Create(ctx, input)
}

// SyncLatestVersion is the resolver for the syncLatestVersion field.
func (r *mutationResolver) SyncLatestVersion(ctx context.Context, id string) (*model.Game, error) {
	game, err := r.Repo.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	if game == nil {
		return nil, fmt.Errorf("game %s not found", id)
	}
	if game.VndbID == nil {
		return nil, fmt.Errorf("game %s has no VNDB ID", id)
	}

	release, err := r.VNDB.GetLatestRelease(ctx, *game.VndbID)
	if err != nil {
		return nil, err
	}
	if release == nil {
		return game, nil
	}
	return r.Repo.UpdateLatestVersion(ctx, id, release.Version)
}

// ExportLibrary is the resolver for the exportLibrary field.
func (r *mutationResolver) ExportLibrary(ctx context.Context) (string, error) {
	return r.Repo.Export(ctx)
}

// ImportLibrary is the resolver for the importLibrary field.
func (r *mutationResolver) ImportLibrary(ctx context.Context, json string) (bool, error) {
	err := r.Repo.Import(ctx, json)
	return err == nil, err
}

// ImportFromF95 is the resolver for the importFromF95 field.
func (r *mutationResolver) ImportFromF95(ctx context.Context, threadURL string) (*model.Game, error) {
	if !r.F95.IsLoggedIn() {
		return nil, fmt.Errorf("not logged in to F95Zone — set credentials in Settings")
	}

	game, err := r.F95.GetGame(ctx, threadURL)
	if err != nil {
		return nil, fmt.Errorf("scrape F95Zone thread: %w", err)
	}

	f95ID := game.ThreadID
	input := model.GameInput{
		Title:         game.Title,
		Developer:     &game.Developer,
		CoverURL:      &game.CoverURL,
		Tags:          game.Tags,
		LatestVersion: &game.Version,
		Description:   &game.Description,
		F95Id:         &f95ID,
	}
	return r.Repo.Create(ctx, input)
}

// SyncF95Version is the resolver for the syncF95Version field.
func (r *mutationResolver) SyncF95Version(ctx context.Context, id string) (*model.Game, error) {
	game, err := r.Repo.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	if game == nil {
		return nil, fmt.Errorf("game %s not found", id)
	}
	if game.F95Id == nil || *game.F95Id == "" {
		return nil, fmt.Errorf("game %s has no F95Zone thread ID", id)
	}
	if !r.F95.IsLoggedIn() {
		return nil, fmt.Errorf("not logged in to F95Zone — set credentials in Settings")
	}

	threadURL := fmt.Sprintf("https://f95zone.to/threads/%s/", *game.F95Id)
	// Invalidate cache so we get fresh data.
	r.F95.InvalidateCache(threadURL)

	f95Game, err := r.F95.GetGame(ctx, threadURL)
	if err != nil {
		return nil, fmt.Errorf("scrape F95Zone thread: %w", err)
	}
	if f95Game.Version == "" {
		return game, nil
	}
	return r.Repo.UpdateLatestVersion(ctx, id, f95Game.Version)
}

// SetF95Credentials is the resolver for the setF95Credentials field.
func (r *mutationResolver) SetF95Credentials(ctx context.Context, username string, password string) (bool, error) {
	if err := r.Settings.Set(ctx, "f95_username", username); err != nil {
		return false, err
	}
	if err := r.Settings.Set(ctx, "f95_password", password); err != nil {
		return false, err
	}

	// Attempt login immediately.
	err := r.F95.Login(ctx, username, password)
	return err == nil, err
}

// TestF95Connection is the resolver for the testF95Connection field.
func (r *mutationResolver) TestF95Connection(ctx context.Context) (bool, error) {
	if r.F95.IsLoggedIn() {
		return true, nil
	}

	username, password, err := r.Settings.GetF95Credentials(ctx)
	if err != nil {
		return false, err
	}
	if username == "" || password == "" {
		return false, fmt.Errorf("F95Zone credentials not configured")
	}

	err = r.F95.Login(ctx, username, password)
	return err == nil, err
}

// SyncAllF95Versions is the resolver for the syncAllF95Versions field.
func (r *mutationResolver) SyncAllF95Versions(ctx context.Context) (*model.SyncResult, error) {
	result := r.Syncer.SyncAll(ctx)
	errors := result.Errors
	if errors == nil {
		errors = []string{}
	}
	return &model.SyncResult{
		Total:   result.Total,
		Updated: result.Updated,
		Errors:  errors,
	}, nil
}

// Games is the resolver for the games field.
func (r *queryResolver) Games(ctx context.Context, filter *model.GameFilter) ([]*model.Game, error) {
	return r.Repo.List(ctx, filter)
}

// Game is the resolver for the game field.
func (r *queryResolver) Game(ctx context.Context, id string) (*model.Game, error) {
	return r.Repo.Get(ctx, id)
}

// SearchVndb is the resolver for the searchVNDB field.
func (r *queryResolver) SearchVndb(ctx context.Context, query string, page *int, adultsOnly *bool) (*model.VNDBPage, error) {
	p := 1
	if page != nil {
		p = *page
	}
	adult := false
	if adultsOnly != nil {
		adult = *adultsOnly
	}

	resp, err := r.VNDB.Search(ctx, query, p, adult)
	if err != nil {
		return nil, err
	}

	results := make([]*model.VNDBResult, 0, len(resp.Results))
	for _, vn := range resp.Results {
		results = append(results, vnToResult(&vn))
	}

	return &model.VNDBPage{
		Results: results,
		Count:   resp.Count,
		More:    resp.More,
	}, nil
}

// GetVNDBGame is the resolver for the getVNDBGame field.
func (r *queryResolver) GetVNDBGame(ctx context.Context, vndbID string) (*model.VNDBResult, error) {
	vn, err := r.VNDB.GetVN(ctx, vndbID)
	if err != nil {
		return nil, err
	}
	return vnToResult(vn), nil
}

// SearchF95 is the resolver for the searchF95 field.
func (r *queryResolver) SearchF95(ctx context.Context, query string, page *int) (*model.F95SearchResult, error) {
	if !r.F95.IsLoggedIn() {
		return nil, fmt.Errorf("not logged in to F95Zone — set credentials in Settings")
	}

	p := 1
	if page != nil {
		p = *page
	}

	page_data, err := r.F95.Search(ctx, query, p)
	if err != nil {
		return nil, err
	}

	results := make([]*model.F95SearchItem, 0, len(page_data.Items))
	for _, item := range page_data.Items {
		tags := item.Tags
		if tags == nil {
			tags = []string{}
		}
		results = append(results, &model.F95SearchItem{
			ThreadID:  item.ThreadID,
			ThreadURL: item.ThreadURL,
			Title:     item.Title,
			Version:   item.Version,
			Engine:    item.Engine,
			Tags:      tags,
		})
	}

	return &model.F95SearchResult{Results: results, TotalPages: page_data.TotalPages}, nil
}

// GetF95Game is the resolver for the getF95Game field.
func (r *queryResolver) GetF95Game(ctx context.Context, threadURL string) (*model.F95Game, error) {
	if !r.F95.IsLoggedIn() {
		return nil, fmt.Errorf("not logged in to F95Zone — set credentials in Settings")
	}

	game, err := r.F95.GetGame(ctx, threadURL)
	if err != nil {
		return nil, err
	}

	screenshots := game.Screenshots
	if screenshots == nil {
		screenshots = []string{}
	}
	tags := game.Tags
	if tags == nil {
		tags = []string{}
	}

	return &model.F95Game{
		ThreadID:    game.ThreadID,
		ThreadURL:   game.ThreadURL,
		Title:       game.Title,
		Developer:   game.Developer,
		Version:     game.Version,
		CoverURL:    game.CoverURL,
		Description: game.Description,
		Tags:        tags,
		Engine:      game.Engine,
		F95Status:   game.Status,
		Screenshots: screenshots,
	}, nil
}

// AppSettings is the resolver for the appSettings field.
func (r *queryResolver) AppSettings(ctx context.Context) (*model.AppSettings, error) {
	username, err := r.Settings.Get(ctx, "f95_username")
	if err != nil {
		return nil, err
	}
	return &model.AppSettings{
		F95Username:  username,
		F95Connected: r.F95.IsLoggedIn(),
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
