ALTER TABLE games ADD COLUMN IF NOT EXISTS f95_id TEXT;
CREATE INDEX IF NOT EXISTS games_f95_id_idx ON games(f95_id);

CREATE TABLE IF NOT EXISTS settings (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL DEFAULT ''
);
